Wishlist
wolox-training/lz-react-native pull request #17
Opened 2018-02-09 16:45 UTC by LucasZibell

## Summary
The rent and wishlist button can now be clicked on to execute their respective tasks.

## TrelloCard 
 https://trello.com/c/1bgZoZIK/24-alquileres-y-wishlist

2018-02-09 18:46 UTC, IgnacioAbadie commented on React/my-app/src/components/MultiStateButton/index.js
> +  NO_SE_ENCUENTRA
should be in english!

2018-02-09 19:38 UTC, IgnacioAbadie requested changes

2018-02-09 19:38 UTC, IgnacioAbadie commented on React/my-app/src/redux/accounts/actions.js
> +        dispatch({
throw new Error(response.error)
so you avoid to repeat the dispatch code

2018-02-09 19:38 UTC, IgnacioAbadie commented on React/my-app/src/redux/rents/actions.js
> +      console.log(window.localStorage.userId);
remove this console log

2018-02-09 19:38 UTC, IgnacioAbadie commented on React/my-app/src/redux/rents/actions.js
> +      console.log(window.localStorage.userId);
remove log

2018-02-09 19:38 UTC, IgnacioAbadie commented on React/my-app/src/redux/rents/actions.js
> +const bookAvailable = books => {
move all functions that work with arrays into a `arraysUtils.js` on `Utils` folder

2018-02-09 19:38 UTC, IgnacioAbadie commented on React/my-app/src/redux/rents/actions.js
> +const responseOK = bookResponse => {
same with this.
Move to `requestUtils.js`

2018-02-09 19:38 UTC, IgnacioAbadie commented on React/my-app/src/redux/rents/actions.js
> +        if (bookAvailable(bookResponse.data)) {
should be only the rents response here like state.

So, if you have to do some of logic that corresponde to the View, do it on the View!

2018-02-09 19:38 UTC, IgnacioAbadie commented on React/my-app/src/service/accounts.js
> +// export const getWishlist = id => {
remove commented code

2018-02-14 14:04 UTC, pabloferro requested changes

2018-02-14 14:04 UTC, pabloferro commented on React/my-app/src/components/MultiStateButton/index.js
> +const MultiStateButton = ({ available, text, disabled, onClick }) => {
You can use destructuring here to pass some props to the button.
```js
const MultiStateButton = ({ available, text, ...buttonProps }) => {
```
```js
<button
  className={`button ${!available && "wishlist-button"}`}
  {...butonProps}
>
```

2018-02-14 14:04 UTC, pabloferro commented on React/my-app/src/components/MultiStateButton/index.js
> +export default MultiStateButton;
I would move this component to `book_detail/components/` and give it a proper name since it's only used there (Like `RentButton`?)

2018-02-14 14:04 UTC, pabloferro commented on React/my-app/src/components/MultiStateButton/index.js
> +export default MultiStateButton;
Another approach would be to move all the logic to the book detail component and keep the MultiState button generic.

2018-02-14 14:04 UTC, pabloferro commented on React/my-app/src/components/MultiStateButton/styles.css
> +}
Remove empty selector

2018-02-14 14:04 UTC, pabloferro commented on React/my-app/src/components/MultiStateButton/styles.css
> +.button_box {
We use camel case for css classes.
If you are using snake case in all classes we can keep it.

2018-02-14 14:04 UTC, pabloferro commented on React/my-app/src/components/MultiStateButton/styles.css
> +.in_possesion {
Unused class?

2018-02-14 14:04 UTC, pabloferro commented on React/my-app/src/components/MultiStateButton/styles.css
> +.unavailable {
Unused class?

2018-02-14 14:04 UTC, pabloferro commented on React/my-app/src/redux/accounts/actions.js
> +      if (responseOK(response)) {
Why do you need this validation?

2018-02-14 14:04 UTC, pabloferro commented on React/my-app/src/utils/arrayUtils.js
> +};
I'd move these functions to the component (or another file in it's folder). Utils should be generic.

2018-02-14 14:04 UTC, pabloferro commented on React/my-app/src/screens/book_detail/index.js
> +      this.setState({
Changing state in componentWillReceiveProps is *generally* not necessary.
Here you can compute this "state" in the render based on props. So this component shouldn't need state.

Also react will call `componentWillReceiveProps` even if the props didn't change so you always need to check if `newProps` is different to `this.props` (or at least the props that you are interested in).

2018-02-14 14:04 UTC, pabloferro commented on React/my-app/src/service/accounts.js
> +export const getAccount = url => {
Unnecessary function 😄

2018-02-14 14:04 UTC, pabloferro commented on React/my-app/src/service/accounts.js
> +export const getAccount = url => {
Either call it getCurrentAccount and use '/user/me' instad of receiving an argument or remove it.

2018-02-14 14:04 UTC, pabloferro commented on React/my-app/src/service/accounts.js
> +  return postAccount(`/users/${window.localStorage.userId}/wishes`, body);
Same with `postAccount`, It does the same as api.post.
You can refactor it to just receive the `userId` and body or just remove it.

2018-02-14 14:04 UTC, pabloferro commented on React/my-app/src/service/books.js
> +  return api.get(url);
Same here, use the url or else the function is the same as api.get (but with less options)

2018-02-15 12:40 UTC, merged